# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run format
        run: pnpm format:check
      - name: Run lint
        run: pnpm lint
      - name: Run build
        run: pnpm build
      - name: Run tests
        run: pnpm test
