# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
          run_install: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run format
        run: pnpm format:check
      - name: Run lint
        run: pnpm lint
      - name: Run build
        run: pnpm build
      - name: Run tests
        run: pnpm test
